Minor code changes
Epix-Incorporated/Adonis pull request #1023
Opened 2023-03-13 07:04 UTC by P3tray

2023-03-13 07:04 UTC, P3tray commented
i still dont know why a years worth of commits show

2023-03-13 07:04 UTC, P3tray commented
stupid github

2023-03-13 07:04 UTC, P3tray commented
not my problem

2023-03-13 15:06 UTC, ccuser44 requested changes

2023-03-13 15:06 UTC, ccuser44 commented on MainModule/Server/Commands/Fun.lua
> +						end
This code has improper intending

2023-03-13 15:06 UTC, ccuser44 commented on MainModule/Server/Commands/Fun.lua
> +				spinGryo.Mode = Enum.OrientationAlignmentMode.OneAttachment
Gyro instead of Gryo

2023-03-14 08:10 UTC, P3tray commented on MainModule/Server/Commands/Fun.lua
> +				spinGryo.Mode = Enum.OrientationAlignmentMode.OneAttachment
:(

2023-03-14 08:10 UTC, P3tray commented on MainModule/Server/Commands/Fun.lua
> +						end
:(

2023-03-14 08:11 UTC, P3tray commented
You made me close my PR :(

2023-03-14 08:11 UTC, closed without merging

2023-03-14 08:37 UTC, ccuser44 commented
?

2023-03-15 08:29 UTC, P3tray commented
> ?

:(

2023-03-15 20:41 UTC, WaviestBalloon commented
P3foodtray is upset

2023-03-20 07:10 UTC, P3tray commented
> P3foodtray is upset

:(