Fix false positive in some games with AntiKick
Epix-Incorporated/Adonis pull request #1045
Opened 2023-04-01 15:05 UTC by L8X

2023-04-01 15:27 UTC, watameln reviewed
Explain to me when this happens like what action so I can recreate it

2023-04-01 15:29 UTC, watameln commented
Do you happen to know if the game has any plugins

2023-04-01 15:37 UTC, watameln commented
Its most likely a plugin/script in the game causing the kick.

2023-04-01 15:51 UTC, ccuser44 commented
> > Do you happen to know if the game has any plugins
> 
> Sadly not, I'm not a developer of that game nor do I know anyone who is, it's possible though. /shrug

This is already fixed by:

- #959 This issue fixed `:unincognito`
- #778 This issue fixes invalid workspace names

But the first one isn't committed to the Adonis release, meaning it's fixed but an update hasn't been released.
The second issue is fixed by #778 pull request but it's not merged by Sceleratis yet.

2023-04-01 15:52 UTC, ccuser44 commented
So #778 fixes probably what the issue is.

What the issue the pull fixes is if the workspace name is blank. Ie. ""

**So before Sceleratis merges #778 you can set `Workspace` name to something else than a blank string!**

2023-04-01 15:57 UTC, ccuser44 commented
> > So #778 fixes probably what the issue is.
> > What the issue the pull fixes is if the workspace name is blank. Ie. ""
> > **So before Sceleratis merges #778 you can set `Workspace` name to something else than a blank string!**
> 
> I don't think it will, I got this screenshot from one of the people who told me about this: ![image](https://user-images.githubusercontent.com/49875377/229301128-83240fbb-b08b-4c8e-9359-461e469a6f13.png)
> 
> They're not an exploiter, so I don't get how this would even fire off for them.

What method did it show? Like method1, method2, method3?

2023-04-01 15:59 UTC, ccuser44 commented
> > > > So #778 fixes probably what the issue is.
> > > > What the issue the pull fixes is if the workspace name is blank. Ie. ""
> > > > **So before Sceleratis merges #778 you can set `Workspace` name to something else than a blank string!**
> > > 
> > > 
> > > I don't think it will, I got this screenshot from one of the people who told me about this: ![image](https://user-images.githubusercontent.com/49875377/229301128-83240fbb-b08b-4c8e-9359-461e469a6f13.png)
> > > They're not an exploiter, so I don't get how this would even fire off for them.
> > 
> > 
> > ~What method did it show? Like method1, method2, method3?~ Edit: Nvm it's method2 i can see the screenshot
> 
> I just asked them anyway, they said it initially says method1 then changes instantly to method2 after the first kick message appears.

Is the workspace name a blank string. Or does it become a blank string?

2023-04-01 16:12 UTC, ccuser44 commented
> > > > > > So #778 fixes probably what the issue is.
> > > > > > What the issue the pull fixes is if the workspace name is blank. Ie. ""
> > > > > > **So before Sceleratis merges #778 you can set `Workspace` name to something else than a blank string!**
> > > > > 
> > > > > 
> > > > > I don't think it will, I got this screenshot from one of the people who told me about this: ![image](https://user-images.githubusercontent.com/49875377/229301128-83240fbb-b08b-4c8e-9359-461e469a6f13.png)
> > > > > They're not an exploiter, so I don't get how this would even fire off for them.
> > > > 
> > > > 
> > > > ~What method did it show? Like method1, method2, method3?~ Edit: Nvm it's method2 i can see the screenshot
> > > 
> > > 
> > > I just asked them anyway, they said it initially says method1 then changes instantly to method2 after the first kick message appears.
> > 
> > 
> > Is the workspace name a blank string. Or does it become a blank string?
> 
> ![image](https://user-images.githubusercontent.com/49875377/229301519-9e9c2e75-6ae5-401c-a37b-57584e08b1f1.png)
> 
> Got a friend to go in with Dex, it's definitely Workspace. By the way, the user corrected themselves after I asked about if they saw method 3 on the kick messages, and guess what; they did after all. I think it's safer to disable these detections for now until we find the root cause, as we could theoretically be causing games to lose players if this is more widespread than we think it is.

By looking at the messages it appears that the Roblox namecalls do not error. Instead of disabling the checks you should only disable the ones which use namecalls.

I still haven't been able to reproduce the issue in the game.

Also are you sure that are there any scripts that might set workspace name? Check if workspace name is something different

2023-04-01 16:15 UTC, ccuser44 commented
Just asking for coriosity. What devices are they using. Are they using a Windows beta app?

Also ask what version of the Roblox client are they using. Ask them to send a screenshot of this \\/
![image](https://user-images.githubusercontent.com/68124053/229302244-8633cb40-df0c-4eb1-ab48-c66b192bdb47.png)

2023-04-01 16:19 UTC, ccuser44 commented
> Both my friend and the user having the issue are using the latest version

Can you show me the percise issue they are getting. I haven't been able to reproduce this in that game.

2023-04-01 16:20 UTC, ccuser44 commented
> Both my friend and the user having the issue are using the latest version

Oops I meant can you show me the direct version of Escape Menu > Help > Version container

2023-04-01 16:26 UTC, ccuser44 commented
I can't reproduce this issue and I didn't find anyone else having this issue in the game, in the group or in their discord server (or at least they haven't reported so)

2023-04-01 16:32 UTC, ccuser44 requested changes

2023-04-01 16:32 UTC, ccuser44 commented on MainModule/Client/Core/Anti.lua
>  						success2 or string.match(err2, "^Kick is not a valid member of Workspace \"(.+)\"$") ~= workspace.Name
Instead of setting the detection to log. You should disable the success2 checks. Because it appears to be triggered by namecalls.

2023-04-01 16:32 UTC, ccuser44 commented on MainModule/Client/Core/Anti.lua
>  									err2 ~= "Cannot kick a non-local Player from a LocalScript"
Here too.

2023-04-01 16:39 UTC, ccuser44 commented on MainModule/Client/Core/Anti.lua
>  						success2 or string.match(err2, "^Kick is not a valid member of Workspace \"(.+)\"$") ~= workspace.Name
> > Instead of setting the detection to log. You should disable the success2 checks. Because it appears to be triggered by namecalls.
> 
> It's triggering all 3 methods though in my user's case.

The last method would only be triggered if an error happened in one of the 2 previous detections

2023-04-01 16:42 UTC, ccuser44 commented on MainModule/Client/Core/Anti.lua
>  						success2 or string.match(err2, "^Kick is not a valid member of Workspace \"(.+)\"$") ~= workspace.Name
> > > > Instead of setting the detection to log. You should disable the success2 checks. Because it appears to be triggered by namecalls.
> > > 
> > > 
> > > It's triggering all 3 methods though in my user's case.
> > 
> > 
> > The last method would only be triggered if an error happened in one of the 2 previous detections
> 
> Pretty sure that is what happens though... I mean they are literally triggering every detection we have for antikick, safer to just disable it entirely.

Could it be possible that you provided a screenshot of the client version via `Escape Menu` > `Help` > `Bottom version bar` of the people affected? It looks like what I sent in the screenshot

2023-04-01 16:46 UTC, ccuser44 commented on MainModule/Client/Core/Anti.lua
>  						success2 or string.match(err2, "^Kick is not a valid member of Workspace \"(.+)\"$") ~= workspace.Name
> > > > > > Instead of setting the detection to log. You should disable the success2 checks. Because it appears to be triggered by namecalls.
> > > > > 
> > > > > 
> > > > > It's triggering all 3 methods though in my user's case.
> > > > 
> > > > 
> > > > The last method would only be triggered if an error happened in one of the 2 previous detections
> > > 
> > > 
> > > Pretty sure that is what happens though... I mean they are literally triggering every detection we have for antikick, safer to just disable it entirely.
> > 
> > 
> > Could it be possible that you coukd provide a screenshot of the client version via `Escape Menu` > `Help` > `Bottom version bar` of the people affected? It looks like what I sent in the screenshot
> 
> https://media.discordapp.net/attachments/1060607362240622652/1091760361964834856/image.png

You told me that one of these people used dex to see the workspace name

Are you sure that these people do not have an exploit injected accidentally. Synapse for example has an auto inject, they might have an auto inject accidentally enabled but don't see an executor window because not all auto injects show an executor window

2023-04-02 07:34 UTC, ccuser44 commented
Was this an april fools joke? (Just asking)

2023-04-02 08:12 UTC, ccuser44 commented
Actually nevermind this is a bug on Robloxes side

![image](https://user-images.githubusercontent.com/68124053/229340720-8cf48de7-53a7-40c2-86d9-a567bb07a45f.png)

The only way this can be fixed is if Roblox fixes this.

2023-04-05 14:24 UTC, ccuser44 commented
Nvm this has to be an april fools joke.

```lua
workspace:Kick("Some string")
```

Should always error.

2023-05-28 17:25 UTC, closed without merging