Fixed Noclip and Clip command
Epix-Incorporated/Adonis pull request #1165
Opened 2023-07-12 23:24 UTC by kaiserandaxl

I made both the Noclip and Clip command be more readable and actually work.

2023-07-31 13:43 UTC, karl-police commented
I tested your changes, and ``:unnoclip`` still let me walk through walls.

2023-07-31 13:45 UTC, karl-police commented on MainModule/Server/Dependencies/Assets/Clip.client.lua
> +script:Destroy()
Is this even being used?

2023-07-31 13:46 UTC, karl-police requested changes
What is "Clip" for?
Is it just to unnoclip?

ADONIS_NoClip is not inside Humanoid, so it's always ``nil``, and that's why unclip doesn't work.

You should change this, I just got ``:unnoclip`` to work by changing that.

I don't see what ``:clip`` is supposed to even do to see differences.

2023-07-31 15:43 UTC, kaiserandaxl commented
The reason it won't work is because the Clip script isn't yet in the dependencies, I have made those changes to where if Clip was inside of dependencies

@karl-police

2023-07-31 15:51 UTC, kaiserandaxl commented
Also to answer your question about how this fixes it is this.

Before it was deleting the the script that changed the players state and made them have the ability to walk through walls, well this doesn't work anymore and they still are able to walk through walls so I made one extra script

This other script is supposed to give them the ability to collide with walls and objects again and then change the HumanoidState to 18 (none) which then gives roblox the abiltiy to set the state to whatever they want.

2023-07-31 15:55 UTC, karl-police commented
> The reason it won't work is because the Clip script isn't yet in the dependencies, I have made those changes to where if Clip was inside of dependencies
> 
> @karl-police

I put it in there on Studio when testing for myself.

2023-07-31 15:56 UTC, karl-police commented
Unnoclip still won't work because the code is still looking inside Humanoid.

2023-07-31 17:01 UTC, kaiserandaxl commented
Fixed it

2023-08-02 12:26 UTC, karl-police commented
> Fixed it

Did you test it as well?

2023-08-02 12:31 UTC, karl-police requested changes
prolly you wanna fix it

2023-08-02 12:54 UTC, kaiserandaxl commented
@karl-police you gonna look and find any errors

2023-08-02 22:06 UTC, karl-police approved these changes

2023-08-08 11:48 UTC, karl-police requested changes
Instead of renaming "Clip" I think you renamed "Clipper" to "DisableNoclip", but there's still code that need that dependency "Clipper".

Rename DisableNoclip back to Clipper. And re-name "Clip" to DisableNoclip instead.

2023-08-09 11:11 UTC, karl-police approved these changes

2023-08-09 11:13 UTC, karl-police commented
@Sceleratis 
@Expertcoderz 

It fixes Noclip and Clip aka. Unnoclip

2023-08-12 04:52 UTC, WalkerOfBacon reviewed
This works however the notification doesnt show up when running both :noclip and :clip

2023-08-12 11:58 UTC, kaiserandaxl commented
Do you have command feedback enabled in settings

@WalkerOfBacon

2023-08-13 13:50 UTC, karl-police commented
@Expertcoderz I tested it, you can merge it.

2023-08-13 18:11 UTC, WalkerOfBacon commented
> Do you have command feedback enabled in settings
> 
> @WalkerOfBacon

Not sure

2023-09-17 09:49 UTC, LiveFireExercise commented
Gonna test this one sec

2023-09-17 09:59 UTC, LiveFireExercise commented
<img width="906" alt="image" src="https://github.com/Epix-Incorporated/Adonis/assets/64012878/63eb1efb-1c39-4988-a9a9-2d3a97c53425">
yeah uh

2023-09-17 10:03 UTC, LiveFireExercise commented
Also this PR has some weird effects on the :fly command, might wanna look at that

2023-09-17 10:58 UTC, watameln commented
why not just use the kohls admin noclip and clip :trollface:

2023-10-30 06:49 UTC, squiddickod approved these changes

2023-11-12 19:55 UTC, Dimenpsyonal commented
Idk why you approved the changes because it doesn't work

2023-11-14 00:40 UTC, WalkerOfBacon approved these changes
@Dimenpsyonal uhhhm actually it works

2023-11-14 00:43 UTC, WalkerOfBacon commented
and fly works normally too

2023-11-14 16:15 UTC, WalkerOfBacon commented
fix lint smh

2023-11-14 16:27 UTC, kaiserandaxl commented
Is it gonna be put in yes or no, if not tell me the error so it can be fixed and the error removed

2023-11-14 16:28 UTC, Dimenpsyonal commented
If it works then I'll put it in :)

2023-11-14 16:55 UTC, ccuser44 commented
![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/ca679213-9417-4176-b705-2c6e95181a2a)
The lint errors do not come as a part of this pull

2023-11-14 17:25 UTC, Dimenpsyonal commented
Yes

2023-12-19 13:27 UTC, Dimenpsyonal commented
Make sure to include proof of functionality :)

2023-12-21 12:50 UTC, SuperCater approved these changes

2023-12-30 16:32 UTC, closed without merging