Fixed a possible end of the world scenario.
Epix-Incorporated/Adonis pull request #1183
Opened 2023-08-08 11:34 UTC by P3tray

[ Removed by Reddit ]

2023-08-08 12:11 UTC, btt-t requested changes
Why change the spelling to that?

2023-08-08 12:44 UTC, watameln commented
Improper Formatting, Passive Voice Misuse. Fix now 😠

2023-08-09 07:17 UTC, P3tray commented
> Improper Formatting, Passive Voice Misuse. Fix now 😠

😊

2023-08-12 09:19 UTC, ccuser44 approved these changes

2023-08-12 10:44 UTC, Expertcoderz approved these changes

2023-08-12 10:45 UTC, merged