Make `:avataritem` be accessible without Donor
Epix-Incorporated/Adonis pull request #1187
Opened 2023-08-12 09:23 UTC by ccuser44

Before the commit https://github.com/Epix-Incorporated/Adonis/commit/6f052c4860cb41d0b6d284983f34d98af9cf3206 was made you could use `:avataritem` without having donor.

This reverts the commits behavior to achieve the same effect.

2023-08-12 21:38 UTC, moo1210 requested changes
This isn't the :avataritem command, this is the !avataritem command, which is intended for donors.

2023-08-13 01:24 UTC, closed without merging

2023-08-17 11:35 UTC, ccuser44 commented
:(

2023-08-17 11:35 UTC, ccuser44 commented
> This isn't the :avataritem command, this is the !avataritem command, which is intended for donors.

I was talking about the donor command

2023-08-17 17:39 UTC, moo1210 commented
> > This isn't the :avataritem command, this is the !avataritem command, which is intended for donors.
> 
> I was talking about the donor command

Which is, obviously intended for donors, per the reason it's in Donors.lua, the only reason this existed is because of a oversight when I converted the avatar item commands to use humanoid descriptors in #681, I must've not set the permission level to Donors, but had the donors Boolean to true. I guess no maintainer or me never noticed such until a few days ago, since none of us likely  see them in the commands list (they still get disabled if you disabled donor commands, it was just the permission) unless we're on a alt