Fix atmosphere support
Epix-Incorporated/Adonis pull request #1201
Opened 2023-08-18 22:37 UTC by WalkerOfBacon

figured it out now

2023-08-18 23:00 UTC, LiveFireExercise commented
the problem is that this adonis creates an atmosphere, which may modify the game's lighting in unknown ways

2023-08-18 23:55 UTC, WalkerOfBacon commented
> the problem is that this adonis creates an atmosphere, which may modify the game's lighting in unknown ways

In what ways?

2023-08-19 09:27 UTC, LiveFireExercise commented
> > the problem is that this adonis creates an atmosphere, which may modify the game's lighting in unknown ways
> 
> In what ways?

well atmospheres spawn with some default properties. so i think a better idea would be to only create the atmosphere variables if an atmosphere is present

2023-08-19 13:48 UTC, WalkerOfBacon commented
> well atmospheres spawn with some default properties. so i think a better idea would be to only create the atmosphere variables if an atmosphere is present

I think I did that already.

Adonis will only spawn in a new atmosphere if there isnt an existing one on spawn

2023-08-19 13:48 UTC, WalkerOfBacon commented
It wont spawn it if an atmosphere is already in the game

2023-08-19 14:16 UTC, LiveFireExercise commented
> It wont spawn it if an atmosphere is already in the game

thats the thing, adonis shouldnt spawn one at all.

2023-08-19 14:51 UTC, WalkerOfBacon commented
> thats the thing, adonis shouldnt spawn one at all.

So then how would this work without the error?

2023-08-19 16:04 UTC, LiveFireExercise commented
Simply only assign the variables a value if an atmosphere is present. either that or wrap it in something

2023-08-19 16:05 UTC, WalkerOfBacon commented
Ill try and do that

2023-08-19 16:52 UTC, WalkerOfBacon commented
@LiveFireExercise check it now

2023-08-23 14:28 UTC, ccuser44 requested changes

2023-08-23 14:28 UTC, ccuser44 commented on MainModule/Server/Commands/Moderators.lua
> +					}
You should add code to Process.lua which would do this on startup

2023-08-30 12:47 UTC, WalkerOfBacon commented
intermission

2023-09-16 15:26 UTC, WalkerOfBacon commented
I wonder when this will get merged

2023-09-16 15:28 UTC, LiveFireExercise commented
Well now the variables are only being created if atmosphere exists

2023-09-16 15:30 UTC, WalkerOfBacon commented
> Well now the variables are only being created if atmosphere exists

Is there a problem with that?

2023-09-16 15:31 UTC, LiveFireExercise commented
If an atmosphere command is run then adonis will try and call variables that do not exist

2023-09-16 15:34 UTC, WalkerOfBacon commented
> If an atmosphere command is run then adonis will try and call variables that do not exist

But if the variables dont exist then it would say that the atmosphere doesn't exist

2023-09-16 15:35 UTC, WalkerOfBacon commented
I specifically listed that in the command

2023-09-16 15:35 UTC, WalkerOfBacon commented
The command will only work if there is an atmosphere in Lighting

Otherwise it wont

2023-09-16 15:36 UTC, WalkerOfBacon commented
It's not like its creating a new atmosphere

2023-09-16 15:37 UTC, LiveFireExercise commented
And does it work

2023-09-16 15:47 UTC, WalkerOfBacon commented
> And does it work

Considering its your command you made, im not sure
I just went off by what you made

2023-10-24 23:28 UTC, WalkerOfBacon commented
ok

2023-10-25 09:30 UTC, merged