Update Moderators.lua - Add :outfit command
Epix-Incorporated/Adonis pull request #1228
Opened 2023-10-14 05:24 UTC by wilsontulus

This command works similar to :char, however it will take an OutfitID as a way to get a HumanoidDescription. 

You can get OutfitID by using Roblox Avatar API, for example this is how to get the outfit list of Roblox (User ID 1) which only contains a classic guest avatar: https://avatar.roblox.com/v1/users/1/outfits?itemsPerPage=50

For example this is Outfit ID 19461896 which is a Classic Guest Avatar back in 2011 - early 2016:

![image](https://github.com/Epix-Incorporated/Adonis/assets/54766538/e10b9ec6-d39b-4af3-9229-3241a28bf747)

2023-10-14 09:09 UTC, LiveFireExercise commented
>2 failing and 1 successful checks 
Yes

2023-10-14 09:52 UTC, moo1210 commented
> 2 failing and 1 successful checks

yeah but those were caused by your own commit weeks ago lol

2023-10-14 09:52 UTC, moo1210 requested changes
this command already exists, :bundle

2023-10-14 09:54 UTC, LiveFireExercise commented
i know :trollface:

2023-10-14 09:55 UTC, watameln commented
> i know :trollface:

![image](https://github.com/Epix-Incorporated/Adonis/assets/90981615/31cd7b14-5850-4b63-8b91-329a18847016)

2023-10-14 09:56 UTC, LiveFireExercise commented
die

2023-10-14 09:57 UTC, watameln commented
you too 🍉🍉❤

2023-10-14 09:57 UTC, LiveFireExercise commented
u too 😍

2023-10-14 10:43 UTC, wilsontulus commented
> this command already exists, :bundle

different. :bundle only gets bundle IDs, while this allows you to use an outfit id like outfit loader

2023-10-14 10:45 UTC, wilsontulus commented
of course, `:bundle me 19461896` will error because it only takes bundle IDs.
![image](https://github.com/Epix-Incorporated/Adonis/assets/54766538/5fef2ff5-e7fe-4e19-85bb-349b85e4a74d)

2023-10-14 11:17 UTC, moo1210 approved these changes
> of course, :bundle me 19461896 will error because it only takes bundle IDs.

at some point the logic changed for whatever reason then, to require them to be under a bundle,
https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Server/Commands/Moderators.lua#L6179C8-L6184C11
It used to work a few years ago, but nevertheless...

2023-10-14 15:23 UTC, wilsontulus commented
> > of course, :bundle me 19461896 will error because it only takes bundle IDs.
> 
> at some point the logic changed for whatever reason then, to require them to be under a bundle, https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Server/Commands/Moderators.lua#L6179C8-L6184C11 It used to work a few years ago, but nevertheless...

![image](https://github.com/Epix-Incorporated/Adonis/assets/54766538/5162d456-c195-4632-91ae-85db21a26c86)

really? although GetHumanoidDescriptionFromOutfitId exists in line 6180, it still uses data from GetBundleDetailsAsync which obviously did not work with Outfit IDs.
if you still didn't get what i meant, try some games like outfit loader and you'll see what i mean.
although I could have brought an Outfit Loader-like feature to Adonis, it requires a Roblox Proxy which is obviously not supported here.

2023-10-14 15:30 UTC, wilsontulus commented
![image](https://github.com/Epix-Incorporated/Adonis/assets/54766538/5b8f47c9-53bf-4cbd-9211-60306e029271)
yeah bad request. sad roblox took it down

2023-10-14 20:30 UTC, moo1210 commented
> although I could have brought an Outfit Loader-like feature to Adonis, it requires a Roblox Proxy which is obviously not supported here.

not really, https://create.roblox.com/docs/reference/engine/classes/AvatarEditorService, I’ve already started implementing a few (smaller) parts of this in my mass bug PR with bundle and avatar item (whixh I should probably push the final(?) commit for more load string issues, and mark it as not a draft by now). my (new) mass UI/UX focused PR, that I will submit as a draft shortly after the bug one is not a draft, goes further with this with inventory/catalog searching. Although, I never actually intended to add anything for outfits, it would be pretty much as simple as getting the outfit details and calling avataritem’s function for every asset (exactly like the new bundle command)

> GetBundleDetailsAsync which obviously doesn't work with Outfit IDs today

this wasn’t always the case though, until, once again it was changed at some point in time.

2023-10-15 04:23 UTC, wilsontulus commented
> https://create.roblox.com/docs/reference/engine/classes/AvatarEditorService, I’ve already started implementing a few (smaller) parts of this in my mass bug PR with bundle and avatar item
![image](https://github.com/Epix-Incorporated/Adonis/assets/54766538/544c02ad-61b3-4a0d-92bc-0c9c63cd1a7b)
![image](https://github.com/Epix-Incorporated/Adonis/assets/54766538/c5b87a07-4cbd-4f14-a065-8ff3b9a1664f)
It's pretty limited compared to the Avatar API method since this requires an online player. While the Avatar API method works for any users, whether they're in the same server or not (except deleted accounts though).

2023-10-15 04:53 UTC, moo1210 commented
> but it's pretty limited compared to the Avatar API method since this requires an online player (don't mention the permission system). While the Avatar API method works for any users, whether they're in the same server or not (except deleted accounts though).

I'm a bit confused about what the real-world use case for listing another user's outfits (without their consent) is..? Also, the fact you can fetch other users' outfits through the web APIs, even if their inventory is private, probably is an oversight, and shouldn't be relied on.

2023-10-15 08:00 UTC, wilsontulus commented
> the real-world use case for listing another user's outfits ... the fact you can fetch other users' outfits through the web APIs, even if their inventory is private, probably is an oversight.

Oh, I completely understand it now, sorry for that. Either way, someone could have their own outfit IDs (and others but with consent, since they're the one who gets the IDs) and apply it to other players just like what commands like :char and :bundle can do. That's the reason why I'm trying to submit the command here.

2023-10-28 11:25 UTC, Dimenpsyonal commented
Lint failure 😬

2023-11-09 21:15 UTC, merged