Delete Loader/Loader/Dropper.server.lua
Epix-Incorporated/Adonis pull request #1238
Opened 2023-11-04 20:04 UTC by chesse20

This script only makes it harder to find Adonis on the microprofiler theres no point to it

2023-11-04 20:09 UTC, moo1210 commented
You can just use DebugMode then... I don't disagree the Dropper is kind of dumb though

2023-11-04 20:21 UTC, moo1210 commented
(Also for what it's worth Dropper.server.lua is also likely what keeps causing these moderation issues, _not_ FiOne like everyone at Adonis seems to blame because Roblox Is Banning Lua VMs!!!1111)
https://www.roblox.com/library/2373505175/Adonis-Loader-Sceleratis-Davey-Bones
![image](https://github.com/Epix-Incorporated/Adonis/assets/27241938/09f97f08-793b-4841-acc7-49d06f81b128)

2023-11-08 11:32 UTC, ccuser44 requested changes
You must delete `Loader.meta.json` for this to work.

Otherwise this just bricks Adonis

2023-11-09 21:35 UTC, Sceleratis commented
It's likely no longer necessary but it's original purpose was to clone the loader so the version running could parent itself to nil without potentially messing up anything in studio/with saving (as in, the original disappearing entirely when ran in what used to be known as solo mode.)

Reason was to protect it from malicious server scripts or exploiters that managed to obtain any sort of server-side execution (whether via exploit, vulnerabilities, backdoors, etc.)

2023-11-09 21:41 UTC, Dimenpsyonal commented
Soooo... I assume that's a yes given that server-side exploits are basically impossible now

2023-11-12 09:15 UTC, EasternBloxxer commented
> Soooo... I assume that's a yes given that server-side exploits are basically impossible now

Nothings impossible

2023-11-12 19:51 UTC, Dimenpsyonal commented
Hmm... Thinking I might merge this

2023-11-13 14:31 UTC, merged