Make proxyMt functions respect detections??
Epix-Incorporated/Adonis pull request #1298
Opened 2023-12-09 22:01 UTC by Dimenpsyonal

i didnt test this so yk

2023-12-10 05:14 UTC, moo1210 requested changes
```diff
diff --git a/MainModule/Client/Core/Anti.lua b/MainModule/Client/Core/Anti.lua
index eb268aac..64bfa48c 100644
--- a/MainModule/Client/Core/Anti.lua
+++ b/MainModule/Client/Core/Anti.lua
@@ -124,10 +124,8 @@ return function(Vargs, GetEnv)
 
 	local proxyDetector = newproxy(true)
 
-	do
+	while Settings.Detection and Settings.AllowClientAntiExploit do
 		local proxyMt = getmetatable(proxyDetector)
-		
-		if settings.Detection == true then
 			
 			proxyMt.__index = function() 
 				Detected("kick", "Proxy metaMethod 0x215F")
@@ -197,9 +195,8 @@ return function(Vargs, GetEnv)
 	
 			proxyMt.__metatable = "The metatable is locked"
 		end
-	end
 
-	do
+	while Settings.Detection and Settings.AllowClientAntiExploit do
 		local callStacks = {
 			indexInstance = {},
 			newindexInstance = {},
@@ -417,7 +414,7 @@ return function(Vargs, GetEnv)
 		end)
 
 		Routine(function()
-			while true do
+			while Settings.Detection and Settings.AllowClientAntiExploit do
 				do
 					local source, line, argN, isVararg, name, closure = debug.info(Detected, "slanf")
 					if
@@ -656,7 +653,7 @@ return function(Vargs, GetEnv)
 
 	client.Anti = Anti
 
-	do
+	while Settings.Detection and Settings.AllowClientAntiExploit do
 		local meta = service.MetaFunc
 		local track = meta(service.TrackTask)
 		local opcall = meta(pcall)
diff --git a/MainModule/Client/Plugins/Anti_Cheat.lua b/MainModule/Client/Plugins/Anti_Cheat.lua
index b9d687a4..1de40df6 100644
--- a/MainModule/Client/Plugins/Anti_Cheat.lua
+++ b/MainModule/Client/Plugins/Anti_Cheat.lua
@@ -78,7 +78,7 @@ return function(Vargs)
 
 	local proxyDetector = newproxy(true)
 
-	do
+	while Settings.Detection and Settings.AllowClientAntiExploit do
 		local proxyMt = getmetatable(proxyDetector)
 
 		proxyMt.__index = function()
diff --git a/MainModule/Server/Dependencies/ClientMover.client.lua b/MainModule/Server/Dependencies/ClientMover.client.lua
index f2794404..909f69ca 100644
--- a/MainModule/Server/Dependencies/ClientMover.client.lua
+++ b/MainModule/Server/Dependencies/ClientMover.client.lua
@@ -25,7 +25,7 @@ do
 
 	local proxyDetector = newproxy(true)
 
-	do
+	while Settings.Detection and Settings.AllowClientAntiExploit do
 		local proxyMt = getmetatable(proxyDetector)
 
 		proxyMt.__index = function()
-- 
```

2023-12-10 10:37 UTC, Dimenpsyonal commented
Why is this happening 
<img width="548" alt="image" src="https://github.com/Epix-Incorporated/Adonis/assets/64012878/7b1754b4-b528-4347-b624-a40fcdf66056">

2023-12-10 10:42 UTC, moo1210 commented
`Settings` -> `settings` or add `server.`

2023-12-10 10:46 UTC, Dimenpsyonal commented
Moment
![Uploading image.png…]()

2023-12-13 13:40 UTC, Dimenpsyonal commented
breaking news: i give up

2023-12-13 13:40 UTC, closed without merging