Notify admins what rank they are upon joining
Epix-Incorporated/Adonis pull request #1303
Opened 2023-12-14 21:58 UTC by alau740

This adds a message to the welcome notification telling admins what rank they are (and almost every other admin system i'm aware of on roblox already do this)

It allows admins to understand what permission level they have in a game quicker (instead of having to run `:admins` after they join)

Here is an example for a user with moderators permissions:
![Screenshot 2023-12-14 204300](https://github.com/Epix-Incorporated/Adonis/assets/77434904/53356bb3-ca2f-48ed-a1f6-40db1a96b7da)

It also works with custom ranks; an example is shown here with the 'Helpers' rank, admin level 50:
![Screenshot 2023-12-14 205128](https://github.com/Epix-Incorporated/Adonis/assets/77434904/9dc4d7bc-6553-45d1-a762-97b8fe10e0d9)

## Notice
Please make sure you read the Contributing Guidelines before submitting a pull request. https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md

2023-12-14 22:46 UTC, WalkerOfBacon approved these changes
someone was bound to do this

and that someone is you

2023-12-15 00:24 UTC, AlexanderDarmody commented
Can you remove the "s" at the end of the default ranks so it doesn't look dumb

2023-12-15 00:25 UTC, bigbenster702 approved these changes
:D

2023-12-15 01:13 UTC, SuperCater commented on MainModule/Server/Core/Process.lua
> +						Functions.Notification("Welcome.", "Your rank is ".. rank ..". Click here for commands.", {p}, 15, "MatIcon://Verified user", Core.Bytecode(`client.Remote.Send('ProcessCommand','{Settings.Prefi
Maybe show rank level as well?
```suggestion
						Functions.Notification("Welcome.", `Your rank is {rank} ({level}). Click here for commands.`, {p}, 15, "MatIcon://Verified user", Core.Bytecode(`client.Remote.Send('ProcessCommand','{Settings.Prefix}cmds')`))
```

2023-12-30 21:36 UTC, P3tray requested changes
Do you know who else has dementia?

2023-12-30 21:36 UTC, P3tray commented on MainModule/Server/Core/Process.lua
> +						Functions.Notification("Welcome.", "Your rank is ".. rank ..". Click here for commands.", {p}, 15, "MatIcon://Verified user", Core.Bytecode(`client.Remote.Send('ProcessCommand','{Settings.Prefi
overkill

2024-01-04 11:54 UTC, ccuser44 approved these changes

2024-01-15 09:21 UTC, merged

2024-01-16 06:51 UTC, P3tray commented
they merged the dementia command

2024-01-16 10:18 UTC, Dimenpsyonal commented
Do you know who else has dementia?

2024-01-16 11:03 UTC, P3tray commented
they merged the dementia command

2024-01-16 11:11 UTC, P3tray commented
they merged the dementia command

2024-01-17 12:17 UTC, Dimenpsyonal commented
Do you know who else has dementia?

2024-01-18 07:17 UTC, P3tray commented
they merged the dementia command