Add easter egg for April 1st and October 31st
Epix-Incorporated/Adonis pull request #1510
Opened 2024-05-05 15:40 UTC by ccuser44

Add easter egg for April 1st and October 31st

We do a little trolling

2024-05-05 16:58 UTC, Dimenpsyonal commented
what is lifeoftheparty anyway

2024-05-05 16:59 UTC, ccuser44 commented
> what is lifeoftheparty anyway

Mystery

2024-05-05 17:01 UTC, Dimenpsyonal commented
For all I know this is adding the env virus

2024-05-05 17:01 UTC, ccuser44 commented
> For all I know this is adding the env virus

Run the command `?ILOVEYOU`

2024-05-05 17:02 UTC, Dimenpsyonal commented
well having this effect might be disruptive to games

2024-05-05 17:03 UTC, ccuser44 commented
> well having this effect might be disruptive to games

Just a prank bro ¯\_(ツ)_/¯

2024-05-09 09:48 UTC, SuperCater requested changes

2024-05-09 09:48 UTC, SuperCater commented on MainModule/Client/UI/Default/HelpButton.lua
> +		return
Remove the return statement.

We shouldn't fully disable the help button if this was to be added

2024-05-20 14:43 UTC, Dimenpsyonal commented
After a review of the PR it doesn't appear to stop
<img width="1241" alt="image" src="https://github.com/Epix-Incorporated/Adonis/assets/64012878/3c4ce071-1c69-495a-a72b-49653de0d851">

2024-05-20 16:04 UTC, ccuser44 commented
> After a review of the PR it doesn't appear to stop
> ￼

:clearadonisguis me

2024-05-20 16:05 UTC, ccuser44 commented
Or reset

2024-05-20 16:10 UTC, closed without merging