Update Colorize to use TweenService and task.wait
Epix-Incorporated/Adonis pull request #853
Opened 2022-07-09 21:01 UTC by xvarmkorv2

2022-07-22 16:48 UTC, P3tray requested changes
If the code has been tested by yourself and is working, then please make these further changes.

2022-07-22 16:48 UTC, P3tray commented on MainModule/Client/UI/Colorize.rbxmx
> +			yes.MouseButton1Click:connect(function()
Please don't uncaptialize `:Connect()`

2022-07-22 16:48 UTC, P3tray commented on MainModule/Client/UI/Colorize.rbxmx
> +			no.MouseButton1Click:connect(function()
Please don't uncaptialize `:Connect()`

2022-07-22 16:48 UTC, P3tray commented on MainModule/Client/UI/Colorize.rbxmx
> +		for i,v in ipairs(obj:GetChildren()) do
We recently removed all pairs() and ipairs() functions from our code.

Pleas change `for i,v in ipairs(obj:GetChildren())` to `for i,v in obj:GetChildren()` and re-test your code.

2022-07-24 03:12 UTC, LawMixer approved these changes
I mean, this looks good to me. Just wait for somebody with write access to review and merge it.

2022-07-30 01:44 UTC, Expertcoderz approved these changes

2022-07-30 01:44 UTC, merged