New Highlight Command
Epix-Incorporated/Adonis pull request #916
Opened 2022-10-01 21:47 UTC by DimensionalFusion

Utilising a very obscure Roblox object to do so.

2022-10-02 21:06 UTC, h0nzzz commented
`player` doesnt seem to be defined anywhere (or i might just be dumb)

2022-10-09 09:54 UTC, DimensionalFusion commented
No it’s me

2022-11-01 10:21 UTC, P3tray commented
> No it’s me

fix it then dummy

2022-11-01 10:22 UTC, P3tray requested changes

2022-11-01 10:22 UTC, P3tray commented on MainModule/Server/Commands/Moderators.lua
> +				Highlight.Parent = player
Change `Highlight.Parent = player` to `Highlight.Parent = getplayer()` or whatever basically your an idiot.

2023-01-09 10:21 UTC, joritochip commented
Closing due to no activity to fix issue from pull request author, you can reopen it but if you do also make sure to include a command to un-highlight someone

2023-01-09 10:21 UTC, closed without merging

2023-01-09 13:05 UTC, P3tray commented
@LiveFireExercise your lazy