Fix for fly command breaking when PhysicsSteppingMethod is set to Adaptive
Epix-Incorporated/Adonis pull request #919
Opened 2022-10-04 21:25 UTC by xvarmkorv2

2022-10-25 06:26 UTC, P3tray commented
Oh hey! Deja vu!

Time for this PR to be left open for the next 16 months.

2022-10-25 06:30 UTC, P3tray requested changes
looks good nothing really to scrutinize so approved (⌐■_■)

2022-10-25 06:30 UTC, P3tray commented on MainModule/Server/Dependencies/Assets/Spinner.client.lua
> +  task.wait(1/44)
just make it 0.0227 like a normal person

2022-11-09 13:15 UTC, P3tray approved these changes
👍🏿

2022-11-09 16:19 UTC, DimensionalFusion commented
> 👍🏿

Ew

2022-11-11 18:22 UTC, merged