Legalize nuclear bombs.
Epix-Incorporated/Adonis pull request #945
Opened 2022-11-15 16:07 UTC by setfenv

This monkey known as "el guagua" is bypassing FilteringEnabled with NetworkServer, this behaviour is Israeli and shall not be accepted in modern day society. To patch this we must legalize nuclear bombs.

2022-11-15 16:15 UTC, ItsOaky commented
I agree! I support the legalization of nuclear bombs!
________________________________
From: setfenv ***@***.***>
Sent: Tuesday, November 15, 2022 10:07 AM
To: Epix-Incorporated/Adonis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Epix-Incorporated/Adonis] Legalize nuclear bombs. (PR #945)


This monkey known as "el guagua" is bypassing FilteringEnabled with NetworkServer, this behaviour is Israeli and shall not be accepted in modern day society. To patch this we must legalize nuclear bombs.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Epix-Incorporated/Adonis/pull/945<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DY0iQ4u5FcroiDBJUIMdYTLL8vHZTudlzr8XZ0Q7vY8%3D&reserved=0>

Commit Summary

  *   760799a<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945%2Fcommits%2F760799aa03ee78825146fbc7cc8799d52cad586f&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RbA9KeTEUXpiqVyXcGzXiZjE8v%2F0hxlFSDd9ou8PziI%3D&reserved=0> Legalize nuclear bombs.

File Changes

(1 file<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945%2Ffiles&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bJYwrEPAim9Ma5JtCnTtXsIkpeKSO4Ph1unVUbzHQnk%3D&reserved=0>)

  *   M MainModule/Client/Core/Anti.lua<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945%2Ffiles%23diff-5b44136c4149722d1d0174a25ec6dc37db009198140563f893ce4603db15fa63&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vVOtQRIW%2Bi3fRNL5E43OIzrO6dl0PCnqnJG6XZjnKAg%3D&reserved=0> (5)

Patch Links:

  *   https://github.com/Epix-Incorporated/Adonis/pull/945.patch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945.patch&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sXUWzQ96UPGBMnoCgSD1MGObB8W9tDT3nh%2Bj1jgEsg0%3D&reserved=0>
  *   https://github.com/Epix-Incorporated/Adonis/pull/945.diff<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945.diff&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tb4xYwXgp2n0%2FK5z2RLCL0BYd8V6caYLq9MS8fYMLw0%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DY0iQ4u5FcroiDBJUIMdYTLL8vHZTudlzr8XZ0Q7vY8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYLVURQ4IUVDMVCTB5SMV3TWIOYL3ANCNFSM6AAAAAASBDLY7U&data=05%7C01%7C%7Ce280a7351fa94beb946b08dac7237d5e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041252491603325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lCrS9DDzilyZaM3tk9CQa9VjjYaFN1vpuxd8Cxp9bQg%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-11-15 17:33 UTC, IcePools commented
As IcePools, dominator of the minors, Owner of pedophile gaming organization, I approve this message.

2022-11-15 18:01 UTC, ItsOaky commented
We love tha- WAIT A DAMN MINUTE-
________________________________
From: IcePools ***@***.***>
Sent: Tuesday, November 15, 2022 11:33 AM
To: Epix-Incorporated/Adonis ***@***.***>
Cc: Gavin M ***@***.***>; Comment ***@***.***>
Subject: Re: [Epix-Incorporated/Adonis] Legalize nuclear bombs. (PR #945)


As IcePools, dominator of the minors, Owner of pedophile gaming organization, I approve this message.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945%23issuecomment-1315650736&data=05%7C01%7C%7C75f2c89e1df94ed8292c08dac72f8e51%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041304302364508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A6Qw2HowqhAD58zgm8t7jJxaV21Wqebed%2FGz3RSer6w%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYLVURWVY5AQEHN6YYV4XBDWIPCPZANCNFSM6AAAAAASBDLY7U&data=05%7C01%7C%7C75f2c89e1df94ed8292c08dac72f8e51%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041304302520717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k3o9x%2BsqXwb7tHLtPwYQygfH1KMiPpP1jwb9H3yQqOw%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-11-16 08:29 UTC, P3tray requested changes
I simply don't understand what you're trying to fix, whever this fixes the problem, the unforseen consequences, or why our anti is being updated to fix your problem. @ccuser44 should be consulted as he is the anticheat god.

Each anti update strikes fear into our hearts. Unforseen consequences...
![image](https://user-images.githubusercontent.com/31691973/202128394-935f258e-b763-47a6-98f3-fe2330d3b47d.png)

2022-11-16 14:40 UTC, ItsOaky commented
This is so interesting! I support the legalization on nuclear bombs!
________________________________
From: DimensionalFusion ***@***.***>
Sent: Wednesday, November 16, 2022 2:30 AM
To: Epix-Incorporated/Adonis ***@***.***>
Cc: Gavin M ***@***.***>; Comment ***@***.***>
Subject: Re: [Epix-Incorporated/Adonis] Legalize nuclear bombs. (PR #945)


I simply don't understand what you're trying to fix, whever this fixes the problem, the unforseen consequences, or why our anti is being updated to fix your problem. @ccuser44<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccuser44&data=05%7C01%7C%7Caf7efce442274c946b5208dac7ace46d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041842625330127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3TOdBOr9lxRMKKW7Uuv45kd%2BkEMWUo091rmbBB0Jyr0%3D&reserved=0> should be consulted as he is the anticheat god.

Each anti update strikes fear into our hearts. Unforseen consequences...

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F31691973%2F202128394-935f258e-b763-47a6-98f3-fe2330d3b47d.png&data=05%7C01%7C%7Caf7efce442274c946b5208dac7ace46d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041842625330127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zP9GXgf%2BSh5ue2Bi0%2BEp6qcqgl6rsVPMnVfCa9%2Bl7eQ%3D&reserved=0>

Clearly you are not in with the kids

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F945%23issuecomment-1316593021&data=05%7C01%7C%7Caf7efce442274c946b5208dac7ace46d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041842625330127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IhNGgHAtii%2Bl%2FxPwh9wBcYeyy0uDY9duyO2mEso74gk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYLVURWH5ARTKPPFUVGX3PTWISLUHANCNFSM6AAAAAASBDLY7U&data=05%7C01%7C%7Caf7efce442274c946b5208dac7ace46d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638041842625330127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LWCNktyAjc7jnERq5bA0%2Fsdut%2FIkhNQqowznm%2BRl51g%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-11-17 17:26 UTC, closed without merging