Fix spelling and grammar mistakes
Epix-Incorporated/Adonis pull request #990
Opened 2023-01-26 11:11 UTC by watameln

2023-01-26 13:06 UTC, Expertcoderz requested changes
Looks mostly good, just those few issues that need addressing.

2023-01-26 13:06 UTC, Expertcoderz commented on Loader/Config/Settings.lua
> +settings.ConsoleKeyCode = "Quote"	-- Keybind to open the console; Rebindable per player in user-panel; KeyCodes: https://developer.roblox.com/en-us/api-reference/enum/KeyCode
It's either "userpanel" or "user panel". No hyphen.

2023-01-26 13:06 UTC, Expertcoderz commented on Loader/Config/Settings.lua
> +settings.G_Access = false				-- If enabled allow other scripts to access Adonis using _G.Adonis.Access; Scripts will still be able to do things like _G.Adonis.CheckAdmin(player)
Broken grammar moment. I would suggest inserting a comma.

2023-01-26 13:18 UTC, watameln commented
my crap buggin'... marking stuff as things when I don't want to.

2023-01-26 13:20 UTC, watameln commented on Loader/Config/Settings.lua
> +			MAKE SURE YOU SET settings.DataStoreKey TO SOMETHING RANDOM.
Alright sounds good.

2023-01-26 13:31 UTC, watameln commented
I think I've fixed those few issues that you listed.

2023-01-26 16:28 UTC, NoobBucket commented
you might need to abandon your changes to Settings.lua since it will clash with my re-designing PR of it. i will change the mistakes you've found in my PR

2023-01-26 16:56 UTC, watameln commented
Where can I revert it? Github is confusing

2023-01-28 12:13 UTC, Expertcoderz commented
> you might need to abandon your changes to Settings.lua since it will clash with my re-designing PR of it. i will change the mistakes you've found in my PR

Eh isn't it the job of a maintainer to manually resolve the clashes when merging the PR? Don't ask people to take down their contributions in favor of yours just because they edited the same original file that you changed up in your PR; Git is built to allow for handling issues such as this in a cleaner fashion.

![image](https://user-images.githubusercontent.com/81153405/215265515-b3b6cdf5-679c-4b54-b781-509bbaf7b9f2.png)

2023-01-28 12:23 UTC, Expertcoderz approved these changes

2023-01-28 12:26 UTC, merged

2023-01-28 18:16 UTC, NoobBucket commented
> > you might need to abandon your changes to Settings.lua since it will clash with my re-designing PR of it. i will change the mistakes you've found in my PR
> 
> Eh isn't it the job of a maintainer to manually resolve the clashes when merging the PR? Don't ask people to take down their contributions in favor of yours just because they edited the same original file that you changed up in your PR; Git is built to allow for handling issues such as this in a cleaner fashion.
> 
> ![image](https://user-images.githubusercontent.com/81153405/215265515-b3b6cdf5-679c-4b54-b781-509bbaf7b9f2.png)

then i shall revert my changes